config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  
  # GET /about
  get "/about", to: "about#index", as: :firstLink
  # can use the '/' or not, this is same as above 
  # get "about", to: "about#index"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "/", to: "main#index", as: :secondLink
  root to: "main#index"
  # can use the '/' or not, this is same as above 
  # get "", to: "main#index"
  # also for root, you can use special root keyword
  # root to: "main#index"
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
# 
# password:string (virtual)
# password_confirmation:string (virtual)
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format:{with:/\A[^@\s]+@[^@\s]+\z/, message:"must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that." if Current.user.nil?
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        # flash.now[:notice]="Logged in successfully"
        # flash.now[:alert]="Invalid email or password"
        if session[:user_id]
            @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new

    end
    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            #send email
            PasswordMailer.with(user: @user).reset.deliver_later
        end
        redirect_to root_path, notice: "We have sent a link to reset your password to the registered email"
    end
    def edit
        @user = User.find_signed!(params[:token],purpose:"password_reset")
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert:"Your token has expired. Please try again."
    end
    def update
        @user = User.find_signed!(params[:token],purpose:"password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in."
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit

    end
    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "password updated"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        #params
        # => {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"email@email.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"specified text"}

        #params[:user]
        # => {"email"=>"email@email.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}
        
        #render plain: params[:user]
        @user = User.new(user_params)
        if @user.save
            #using cookies to store user info, you can use "cookies[:user_id] but this is unencrypted and can cause security issues with people changing/accessing the private info on it"
            #instead use session cookies to encrypt the data "session[:user_id], it is set server side so browser cannot tamper with it"
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Account Creation Successful"
        else
            # flash[:alert] = "Something was wrong"
            render :new
        end
    end

    private

    def user_params
        #params.require(:user) is like params[:user] except it returns an error if user is not found
        #permit will allow only those attributes for modification, so that a user cant change maybe an admin field
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome to Scheduled Tweets</h1>
</div>

<%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary" %>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <%if form.object.errors.any?%>
        <div class="alert alert-danger">
            <%form.object.errors.full_messages.each do |message|%>
                <div><%= message %></div>
            <%end%>
        </div>
    <%end%>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class:"form-control", placeholder: "abc123ABC!@#"%>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class:"form-control", placeholder: "abc123ABC!@#"%>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password?</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control", placeholder: "abc@email.com"%>
    </div>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class:"form-control", placeholder: "abc123ABC!@#"%>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class:"form-control", placeholder: "abc123ABC!@#"%>
    </div>
    <div class="mb-3">
        <%= form.submit %>
        <%= form.submit "specified text", class: "btn btn-primary"%>
    </div>

    <div class="mb-3">
        <%= form.submit "Reset", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<%if flash[:notice]%>
<div class="alert mt-4 alert-info" role="alert">
    <%= flash[:notice].inspect %>
</div>
<%end%>
<%if flash[:alert]%>
<div class="alert mt-4 alert-warning" role="alert">
    <%= flash[:alert] %>
</div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ST", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <!---left side of nav bar--->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", firstLink_path, class:"nav-link" %>
        <li/>
        <li class="nav-item">
          <%= link_to "Home", secondLink_path, class:"nav-link" %>
        <li/>
      </ul>

    <!---right side of nav bar--->
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <%if Current.user%>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <!---<%= link_to "Logout", logout_path, method: :delete %>--->
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <%else%>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class:"nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>